GET http://localhost:8080

###
POST http://localhost:8080/v1/auth/register
Content-Type: application/json

{
    "username":"natuan8@gm",
    "password":"1232341965",
    "email":"bolabalo8@gmail.com"
}

###
POST http://localhost:8080/v1/auth/login 
Content-Type: application/json 

{
    "username":"natuan3@gm",
    "password":"1232341965"
}

###
GET http://localhost:8080/v1/user/


###

GET http://localhost:8080/v1/user/
Authorization:  Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmE5NWZmYWJkODBkOTllOGU5MzM3NiIsImFkbWluIjpmYWxzZSwiaWF0IjoxNzE0MTA4MzQxLCJleHAiOjE3MTQxMDg0MDF9.gLIrVDRmkMxLFzR5DXZGp1pNacWnf3eYaMxnmyRppgg


###
DELETE http://localhost:8080/v1/user/662a95ffabd80d99e8e93376

